---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

set: [pipefail]
shopt: [globstar]

vars:
  TALOS_DIR: "{{.ROOT_DIR}}/talos"
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"
  BOOTSTRAP_DIR: "{{.KUBERNETES_DIR}}/bootstrap"

  KUBECONFIG: "{{.ROOT_DIR}}/kubeconfig"

includes:
  bootstrap: .taskfiles/bootstrap
  talos: .taskfiles/talos/Taskfile.yaml

tasks:
  default:
    cmd: task --list-all
    silent: true
