---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: longhorn-s3
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: longhorn-s3
    template:
      data:
        AWS_ACCESS_KEY_ID: "{{ .ACCESS_KEY }}"
        AWS_SECRET_ACCESS_KEY: "{{ .SECRET_KEY }}"
        AWS_ENDPOINTS: https://hel1.your-objectstorage.com
  dataFrom:
    - extract:
        key: s3
