---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app cloudflare-dns-external
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: cloudflare-dns
  install:
    disableSchemaValidation: true # Ref: https://github.com/kubernetes-sigs/external-dns/issues/5206
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    disableSchemaValidation: true # Ref: https://github.com/kubernetes-sigs/external-dns/issues/5206
    remediation:
      retries: 3
  values:
    fullnameOverride: *app
    image: # TODO: Remove this block when new chart version is released
      repository: registry.k8s.io/external-dns/external-dns
      tag: v0.16.1
    provider: cloudflare
    env:
      - name: &name CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: &secret cloudflare-dns-secret
            key: *name
      - name: &name CF_ZONE_ID
        valueFrom:
          secretKeyRef:
            name: *secret
            key: *name
    extraArgs:
      - --zone-id-filter=$(CF_ZONE_ID)
      - --cloudflare-dns-records-per-page=1000
      - --cloudflare-proxied
      - --gateway-name=external
      - --gateway-namespace=kube-system
    triggerLoopOnEvent: true
    policy: sync
    sources: ["gateway-httproute"]
    txtOwnerId: external
    txtPrefix: he.
    domainFilters: ["marcocondrache.com"]
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret
