---
# Common tasks for all Raspberry Pi nodes

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade all packages
  apt:
    upgrade: dist
    
- name: Install common packages
  apt:
    name:
      - vim
      - htop
      - git
      - curl
    state: present 