---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app longhorn
  namespace: &namespace longhorn-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  path: ./kubernetes/apps/longhorn-system/longhorn/app
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 15m
  wait: false
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-encryption
  namespace: &namespace longhorn-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: longhorn
      app.kubernetes.io/component: encryption
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  interval: 1h
  path: ./kubernetes/apps/longhorn-system/longhorn/encryption
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 15m
  wait: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-jobs
  namespace: &namespace longhorn-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: longhorn
      app.kubernetes.io/component: jobs
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  interval: 1h
  path: ./kubernetes/apps/longhorn-system/longhorn/jobs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 15m
  wait: true
