---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  values:
    controllers:
      home-assistant:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          # TODO: add home network forwarded through tailscale
          # annotations:
          #   k8s.v1.cni.cncf.io/networks: |
          #     [{
          #       "name":"multus-iot",
          #       "namespace": "network",
          #       "ips": ["10.1.3.151/24"],
          #       "mac": "3e:59:e4:f7:43:08"
          #     }]

          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile:
              type: RuntimeDefault

        containers:
          app:
            image:
              repository: ghcr.io/home-operations/home-assistant
              tag: 2025.3.4
            env:
              TZ: Europe/Rome
              HASS_HTTP_TRUSTED_PROXY_1: 10.0.0.0/8
            resources:
              requests:
                cpu: 10m
                memory: 512Mi
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

          code-server:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.98.2@sha256:9ed588a05d4e81aa464e753a409bc3b2b93267323d1c3975fbddf6f9aef84c26
            env:
              TZ: Europe/Rome
            args:
              [
                "--auth",
                "none",
                "--user-data-dir",
                "/config/.vscode",
                "--extensions-dir",
                "/config/.vscode",
                "--port",
                "12321",
                "/config",
              ]
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi

    service:
      app:
        controller: home-assistant
        ports:
          http:
            port: 8123
            primary: true
          code-server:
            port: 12321

    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        size: 10Gi
        storageClass: longhorn-crypto
        globalMounts:
          - path: /config
      logs:
        type: emptyDir
        globalMounts:
          - path: /config/logs
      tts:
        type: emptyDir
        globalMounts:
          - path: /config/tts
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
      venv:
        type: emptyDir
        globalMounts:
          - path: /config/.venv

    route:
      app:
        hostnames:
          - hass.marcocondrache.com
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /code/
            filters:
              - type: URLRewrite
                urlRewrite:
                  path:
                    type: ReplacePrefixMatch
                    replacePrefixMatch: /
            backendRefs:
              - name: home-assistant
                port: 12321
          - backendRefs:
              - name: home-assistant
                port: 8123
