---
# Main playbook for Raspberry Pi cluster setup and management

- name: Configure all nodes
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        
    - name: Upgrade all packages
      apt:
        upgrade: dist
        
    - name: Install common packages
      apt:
        name:
          - vim
          - htop
          - git
          - curl
        state: present

- name: Configure queen nodes
  hosts: queens
  become: true
  tasks:
    - name: Set hostname
      hostname:
        name: "{{ inventory_hostname }}"

- name: Configure worker nodes
  hosts: workers
  become: true
  tasks:
    - name: Set hostname
      hostname:
        name: "{{ inventory_hostname }}"
