apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: backup
  namespace: longhorn-system
spec:
  concurrency: 2
  cron: "0 0 * * *"
  name: backup
  retain: 7
  task: backup
  groups:
    - default
