apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: trim
  namespace: longhorn-system
spec:
  concurrency: 1
  cron: "0 0 * * 0"
  name: trim
  retain: 7
  task: trim
  groups:
    - default
