---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: longhorn-crypto
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: longhorn-crypto
    template:
      data:
        CRYPTO_PBKDF: "{{ .CRYPTO_PBKDF }}"
        CRYPTO_KEY_SIZE: "{{ .CRYPTO_KEY_SIZE }}"
        CRYPTO_KEY_HASH: "{{ .CRYPTO_KEY_HASH }}"
        CRYPTO_KEY_CIPHER: "{{ .CRYPTO_KEY_CIPHER }}"
        CRYPTO_KEY_PROVIDER: "{{ .CRYPTO_KEY_PROVIDER }}"
        CRYPTO_KEY_VALUE: "{{ .CRYPTO_KEY_VALUE }}"
  dataFrom:
    - extract:
        key: longhorn-crypto
